# Generated by Django 3.0.6 on 2020-05-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adrress', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('chucvu', models.CharField(max_length=100)),
                ('tuoi', models.IntegerField()),
            ],
        ),
    ]
